### ISSUE TITLE
The website links to https://github.com/awalterschulze/protoplay which 404s

### ISSUE THREAD

**Issue by johanbrandhorst** [awalterschulze/awalterschulze.github.io#1]
Not sure what happened with this project, but it's not under that github url anymore!

**Comment by awalterschulze** [comment]
The go proto parser I was using, was still incomplete and I needed to hack into other people's code.
So I deleted it and I found a better use for gopherjs and the playground concept on github using my own validation language http://katydid.github.io/play/
Thanks for reporting :)
